**NUMPY HANDS-ON PRACTICE**
=

*EXERCISE ONE*
=

*1. Import Numpy*
=

In [3]:
# Import NumPy under the conventional alias "np"
import numpy as np

*2. Create an Array*
=

In [4]:
# Start with a plain Python list of temperature readings
temperature_list = [27.5, 29.0, 28.5]

# Convert the list into a 1-D NumPy array
temperature_array = np.array(temperature_list)

print(temperature_array)


[27.5 29.  28.5]


*3. Inspect the Data Type*
=

In [5]:
# Check the array's data type (dtype) to see how NumPy is storing the values
temperature_array.dtype

dtype('float64')

In [6]:
# A nested Python list (list of lists) representing 2 rows x 3 columns of data
weather_data = [
    [27.5, 28.0, 29.5],
    [28.0, 29.0, 30.0]
]
# NumPy automatically turns this into a 2-D array (matrix)
weather_data_array = np.array(weather_data)
print(weather_data_array)

[[27.5 28.  29.5]
 [28.  29.  30. ]]


*EXERCISE TWO*
=

In [7]:
# Plain Python lists holding each person's sales figures
sales_timothy = [10, 15, 20]
sales_brenda = [5, 10, 15]

*1. Try with Python Lists*
=

In [8]:
# Using the "+" operator on plain Python lists concatenates them
# instead of adding the numbers element-wise.
total_sales = sales_timothy + sales_brenda
print(total_sales)

#The code in this cell does not producce the required output i.e [15, 25, 35]
#The code produce the concatenate of the two varaible lists
#The code merge the two list together

[10, 15, 20, 5, 10, 15]


*2. Convert them to Numpy Array*
=

In [9]:
# Convert both sales lists into NumPy arrays
sales_timothy_array = np.array(sales_timothy)
sales_brenda_array = np.array(sales_brenda)

# With NumPy arrays, "+" performs element-wise addition (unlike plain lists)
total_sales_array = sales_timothy_array + sales_brenda_array
print(total_sales_array)

[15 25 35]


*3. Compare the Results*
=

    Approach        |        Results
    ________________|__________________________
    Python Lists    | [10, 15, 20, 5, 10, 15]  
    ________________|__________________________
    Numpy Arrays    |  [15 25 35]

#Numpy is useful because it allow us to carry out addition on the 2-Dimensional Matrix Element-wise

*CHALLENGE*
=

In [10]:
#Sales for both Online and Store from Monday to Friday
online_sales = [20, 15, 10, 10, 30]
store_sales = [15, 16, 45, 10, 5]

#Convert the list of sales to Array
online_sales_array = np.array(online_sales)
store_sales_array = np.array(store_sales)

# Element-wise addition and subtraction across the two arrays (day-by-day)
sum_of_sales = online_sales_array + store_sales_array
difference_in_sales = online_sales_array - store_sales_array

#Display the output
print(sum_of_sales)
print(difference_in_sales)

[35 31 55 20 35]
[  5  -1 -35   0  25]


*EXERCISE THREE*
=

**MINI PROJECT**
=

*Weather Data Quick Analysis with Numpy (Data Analytics / Enviromental Monitoring)*
=

In [23]:
# Import NumPy for the bonus challenge
import numpy as np

In [24]:
# Seven days of recorded temperatures, converted to a NumPy array
temperatures = [27.5, 29.0, 30.5, 28.0, 31.0, 32.5, 30.0]
temperatures_array = np.array(temperatures)
print(temperatures_array)

[27.5 29.  30.5 28.  31.  32.5 30. ]


In [25]:
#The Temperature array is 1D
#It is a Vector

# .dtype shows what type of numbers the array holds (here, floating point)
print(temperatures_array.dtype)
#The data type of the array is "float"

# len() gives the number of elements in the array (i.e. number of readings)
print(len(temperatures_array))
#The Temperature array has 7 observations

float64
7


In [26]:
# Target temperatures for the same seven days, also as a NumPy array
target_temperature = [28.0, 28.0, 29.0, 28.0, 30.0, 30.0, 29.0]
target_temperature_array = np.array(target_temperature)

In [27]:
# Element-wise subtraction: how far each day's recorded temperature is
# from the target (positive = above target, negative = below target)
temperature_difference = temperatures_array - target_temperature_array
print(f"Temperature Difference: {temperature_difference}")

Temperature Difference: [-0.5  1.   1.5  0.   1.   2.5  1. ]


In [28]:
# Add 2 degrees to every recorded temperature (broadcasting: the scalar 2
# is applied to each element of the array automatically)
increase_recorded_temperature = (temperatures_array) + 2
print(f"Increased Recorded Temperature: {increase_recorded_temperature}")

# Same broadcasting applied to the target temperatures
increase_target_temperature = (target_temperature_array) + 2
print(f"Increased Target Temperature: {increase_target_temperature}")


Increased Recorded Temperature: [29.5 31.  32.5 30.  33.  34.5 32. ]
Increased Target Temperature: [30. 30. 31. 30. 32. 32. 31.]


**Business Questions**
=
    
    
    1. Which day appears to have the highest recorded temperature?
    Answer: Saturday
    
    2. On which days was the recorded temperature above the target?
    Answer: Tuesday, Wednesday, Friday, Saturday, Sunday
    
    3. What does the temperature difference tell the weather-monitoring team?
    Answer: The temperature difference makes the weather-monitoring team be aware if the recorded temperature is above or below the terget temperature

    4. Numpy array is more convenient than keeping the temperatures in Python list because it makes the numeric calculation easy,straingt-forward, and faster to work it.

In [29]:
# Print a formatted written summary report of this mini-project (dataset, code used, and findings)
print(f"""
=================================================================
     Weather Data Quick Analysis with NumPy
=================================================================
This project analyzes daily recorded and target temperatures over a seven-day period. It demonstrates how NumPy can efficiently perform numerical 
operations to compare actual data against targets and identify trends.
-----------------------------------------------------------------
import numpy as np
-----------------------------------------------------------------
Dataset:

· Recorded Temperatures: [27.5, 29.0, 30.5, 28.0, 31.0, 32.5, 30.0]
· Target Temperatures: [28.0, 28.0, 29.0, 28.0, 30.0, 30.0, 29.0]
------------------------------------------------------------------
Convert Data to NumPy Arrays:

temperatures_array = np.array(temperatures)
target_temperature_array = np.array(target_temperature)
-----------------------------------------------------------------
Array Inspection

· Data Type: float64
· Length: 7 observations
------------------------------------------------------------------
Numerical Operations:

increase_recorded_temperature = (temperatures_array) + 2
increase_target_temperature = (target_temperature_array) + 2


· Increased Recorded Temperature: [29.5 31. 32.5 30. 33. 34.5 32. ]
· Increased Target Temperature: [30. 30. 31. 30. 32. 32. 31.]
------------------------------------------------------------------
Recorded vs  and Target Temperature Comparison:

temperature_difference = temperatures_array - target_temperature_array
Temperature Difference: {temperature_difference}
------------------------------------------------------------------
Findings:

1. Recorded Temps Exceeded Targets: Temperatures were above target on 5 out of 7 days, peaking on Saturday at +2.5°C.
2. Saturday Was Hottest: Saturday had the highest overall recorded temperature at 32.5°C.
3. Sunday Was the Exception: Sunday was the only day the recorded temp (27.5°C) fell below the target (28.0°C).
------------------------------------------------------------------
Conclusion

NumPy efficiently calculated temperature differences to reveal that recorded temperatures generally trended above targets, with Saturday seeing the 
largest spike. The project highlights NumPy's speed for data analysis.

==================================================================
""")


     Weather Data Quick Analysis with NumPy
This project analyzes daily recorded and target temperatures over a seven-day period. It demonstrates how NumPy can efficiently perform numerical 
operations to compare actual data against targets and identify trends.
-----------------------------------------------------------------
import numpy as np
-----------------------------------------------------------------
Dataset:

· Recorded Temperatures: [27.5, 29.0, 30.5, 28.0, 31.0, 32.5, 30.0]
· Target Temperatures: [28.0, 28.0, 29.0, 28.0, 30.0, 30.0, 29.0]
------------------------------------------------------------------
Convert Data to NumPy Arrays:

temperatures_array = np.array(temperatures)
target_temperature_array = np.array(target_temperature)
-----------------------------------------------------------------
Array Inspection

· Data Type: float64
· Length: 7 observations
------------------------------------------------------------------
Numerical Operations:

increase_recorded_temper

**MINI PROJECT CHALLENGE**
=

In [30]:
# Import NumPy for the bonus challenge
import numpy as np

In [31]:
#This represent the temperature of three locations from Monday - Friday
lagos = [27.5, 29.0, 30.5, 28.0, 31.0]
abuja = [25.0, 28.0, 29.5, 30.0, 32.0]
ibadan = [26.5, 28.5, 29.0, 27.5, 30.0]

# Convert each location's temperature list into a NumPy array
lagos_array = np.array(lagos)
abuja_array = np.array(abuja)
ibadan_array = np.array(ibadan)

print(f"Lagos Temperature: {lagos_array}")
print(f"Abuja Temperature: {abuja_array}")
print(f"Ibadan Temperature: {ibadan_array}")

Lagos Temperature: [27.5 29.  30.5 28.  31. ]
Abuja Temperature: [25.  28.  29.5 30.  32. ]
Ibadan Temperature: [26.5 28.5 29.  27.5 30. ]


**Challenge 1: Which location recorded the highest tempeature on each day?**

    Monday = Lagos
    Tuesday = Lagos
    Wednesday = Lagos
    Thursday = Abuja
    Friday = Abuja

**Challenge 2: Create a calculation that increases every recorded temperature by 1°C.**

In [32]:
#Increase in every recorded temperature by 1 degree C
# Broadcasting adds 1 to every element of each array in one operation
increase_lagos_array = (lagos_array) + 1
increase_abuja_array = (abuja_array) + 1
increase_ibadan_array =(ibadan_array) + 1

print(f"Increased Lagos Temperature: {increase_lagos_array}")
print(f"Increased Abuja Temperature: {increase_abuja_array}")
print(f"Increased Ibadan Temperature: {increase_ibadan_array}")

Increased Lagos Temperature: [28.5 30.  31.5 29.  32. ]
Increased Abuja Temperature: [26.  29.  30.5 31.  33. ]
Increased Ibadan Temperature: [27.5 29.5 30.  28.5 31. ]


**Challenge 3: Create a calculation that compares Lagos temperatures with Abuja temperatures.**

In [33]:
#Temperature difference between lagos and Abuja locations
# Positive values = Lagos warmer that day; negative values = Abuja warmer
temperature_difference = lagos_array - abuja_array
print(f"Lagos and Abuja Temperature Comparison: {temperature_difference}")

Lagos and Abuja Temperature Comparison: [ 2.5  1.   1.  -2.  -1. ]


**Challenge 4: Explain why NumPy becomes increasingly useful as the amount of numerical data grows.**

Answer:

    NumPy becomes increasingly useful for large datasets because of its performance and efficiency. This means mathematical operations on large arrays happen much faster and use significantly less memory. Additionally, it eliminates the need for slow Python for loops by allowing operations to be applied to the entire array at once (element-wise operations).

In [34]:
# Print a formatted written summary report of this challenge (dataset, code used, and findings)
print(f"""
========================================================================
            Weather Station Temperature Analysis
========================================================================
This project analyzes temperature data from three Nigerian locations (Lagos, Abuja, and Ibadan) over a five-day period. The goal is to demonstrate the utility of NumPy arrays for performing rapid numerical operations, comparisons, and transformations on real-world data
-------------------------------------------------------------------------
import numpy as np
-------------------------------------------------------------------------
Dataset
The raw data is provided as Python lists:

· lagos = [27.5, 29.0, 30.5, 28.0, 31.0]
· abuja = [25.0, 28.0, 29.5, 30.0, 32.0]
· ibadan = [26.5, 28.5, 29.0, 27.5, 30.5]
-------------------------------------------------------------------------
Convert Data to NumPy Arrays:

· lagos_array = np.array(lagos)
· abuja_array = np.array(abuja)
· ibadan_array = np.array(ibadan)
-------------------------------------------------------------------------
Array Inspection:

· Lagos Temperature: {lagos_array}
· Abuja Temperature: {abuja_array}
· Ibadan Temperature: {ibadan_array}
-------------------------------------------------------------------------
Numerical Operations
Calculating what the temperatures would be if they all increased by 1°C globally:

increase_lagos_array = (lagos_array) + 1
increase_abuja_array = (abuja_array) + 1
increase_ibadan_array = (ibadan_array) + 1

· Increased Lagos Temperature: {increase_lagos_array}
· Increased Abuja Temperature: {increase_abuja_array}
· Increased Ibadan Temperature: {increase_ibadan_array}
-------------------------------------------------------------------------
Lagos vs Abuja Comparison
Finding the temperature difference between the two locations:

temperature_difference = lagos_array - abuja_array
Lagos and Abuja Temperature Comparison: {temperature_difference}
------------------------------------------------------------------------
Findings:

1. Lagos Dominates Early Week: An analysis of the data shows that Lagos recorded the highest temperature on the first three days (Monday, Tuesday, and Wednesday). The difference is slight, with Lagos only 1.0°C to 2.5°C higher than Abuja during these days.
2. Weekend Shift to Abuja: Interestingly, the trend shifts at the end of the week. Abuja recorded the highest temperature on both Thursday (30.0°C) and Friday (32.0°C). Friday was the single hottest recorded day in the entire dataset.
3. Lagos vs Abuja Temperature Variance: The comparison array ([ 2.5  1.   1.  -2.  -1. ]) reveals that while Lagos was warmer earlier in the week (positive numbers indicate Lagos > Abuja), Abuja became significantly warmer by the end of the week (negative numbers indicate Abuja > Lagos). The shift occurred on Thursday, where Abuja was 2.0°C warmer than Lagos.
-------------------------------------------------------------------------
Conclusion:

Using NumPy allowed us to quickly evaluate and compare temperature variations across multiple locations. By utilizing vectorized operations (like adding 1 to all arrays or subtracting one array from another), we were able to analyze trends efficiently. The data suggests that while Lagos is slightly warmer at the start of the week, Abuja experiences higher peak temperatures towards the weekend.

==========================================================================
""")




            Weather Station Temperature Analysis
This project analyzes temperature data from three Nigerian locations (Lagos, Abuja, and Ibadan) over a five-day period. The goal is to demonstrate the utility of NumPy arrays for performing rapid numerical operations, comparisons, and transformations on real-world data
-------------------------------------------------------------------------
import numpy as np
-------------------------------------------------------------------------
Dataset
The raw data is provided as Python lists:

· lagos = [27.5, 29.0, 30.5, 28.0, 31.0]
· abuja = [25.0, 28.0, 29.5, 30.0, 32.0]
· ibadan = [26.5, 28.5, 29.0, 27.5, 30.5]
-------------------------------------------------------------------------
Convert Data to NumPy Arrays:

· lagos_array = np.array(lagos)
· abuja_array = np.array(abuja)
· ibadan_array = np.array(ibadan)
-------------------------------------------------------------------------
Array Inspection:

· Lagos Temperature: [27.5 29.  30.5 28.  

**BONUS CHALLENGE**
=

*My Prediction at first:*

    print(x + y) output would be [3, 7, 11]
    print(x - y) output would be [1, 1, 1]
    print(x * y) output would be [2, 12, 30]


In [37]:
# Import NumPy for the bonus challenge
import numpy as np

In [38]:
# Two small NumPy arrays to test element-wise arithmetic
x = np.array([2, 4, 6])
y = np.array([1, 3, 5])

# Element-wise operations: each pair of matching positions is combined
print(f"Addition: {x + y}")
print(f"Subtraction: {x - y}")
print(f"Multiplication: {x * y}")


Addition: [ 3  7 11]
Subtraction: [1 1 1]
Multiplication: [ 2 12 30]
